ReactiveDomain/reactive-domain

- src/ReactiveDomain/ReactiveDomain/ReactiveDomain.nuspec
part of fix to remove all warnings
Bug 2562: ReactiveDomain.Tests nuget includes ReactiveDomain.dll instead of taking a dependency on it
http://hoprdsrc03:8080/tfs/Common%20Instrument%20Framework/Greylock/_workitems/edit/2562
> remove Microsoft.net.http dependency

- src/ReactiveDomain/ReactiveDomain/ViewObjects/CommandBuilder.cs
Use existing BuildFireCommand and BuildFireCommandEx to distinguish between commands that take inputs and those that don't. Do the same thing with FromAction (takes a parameterless `Action`) and FromActionEx (takes an `Action<object>`).
Rename BuildPublishCommand to BuildPublishEvent, since it expects a `Func<Event>` not a `Func<Command>`.
Add XML comments to all public methods.
> Command builder refinement

- src/ReactiveDomain.Testing/Specifications/MockRepositorySpecification.cs
- src/ReactiveDomain.Testing/Specifications/MockRepositoryTests.cs
- Expose an `IStreamStoreConnection`, an `IStreamNameBuilder`, and an `IEventSerializer` from `MockRepositorySpecification` to allow read models and other clients to connect to the mock StreamStore when using this test fixture and interact with it seamlessly.
- Fix a bug (unnecessary prefix in the stream name builder) that interfered with GetById.
- Use a new instance of the MockRepositorySpecification for each test in `MockRepositoryTests`.
> MockRepositorySpecification improvements

- .travis.yml
- src/build.props
- tools/CheckAssemblyVersion.ps1
- tools/CreateNuget.ps1
Updates for travis builds
Update yml file to:
1. call CheckAssembly powershell script
2. Restore nugets
3. Build solution (Debug and Release)
4. Run unit tests
5. call CreateNuget powershell script
Add CheckAssembly.ps1 - Checks to make sure build.props is updated from version on master branch
Add CreateNuget.ps1 - Creates beta/release nuget depending on the type of Travis build (push vs api)
Add wget.exe - Used by CheckAssembly.ps1 to clone only the build.props from master branch ( https://www.gnu.org/software/wget/ )
Note:
CheckAssembly.ps1 only runs when branch IS NOT master
CreateNuget.ps1 only runs when branch IS master
> Assembly update build check

- src/ReactiveDomain.Testing/Assert.cs
- src/build.props
The IsOrBecomes methods can now optionally yield at the beginning of execution. This allows them to work with tests of view models that include code that need to run on the "UI thread" or on the Immediate thread when running in unit tests. This option is disabled by default.
> Enhance IsOrBecomes functions for use with reactive view models

- src/ReactiveDomain.UI.Testing/ReactiveDomain.UI.Testing.csproj
- src/ReactiveDomain.UI/ReactiveDomain.UI.csproj
- src/build.props
Enables the use of DynamicData instead of ReactiveList, while still keeping ReactiveList available as deprecated to avoid breaking client applications that use it.
> Update ReactiveUI references to 0.9.22.1

- .travis.yml
- src/ReactiveDomain.Debug.nuspec
- src/ReactiveDomain.Testing.Debug.nuspec
- src/ReactiveDomain.Testing/EventStore/MockStreamStoreConnection.cs
- src/ReactiveDomain.Testing/EventStore/MockStreamStoreConnectionTests.cs
- src/ReactiveDomain.Testing/Foundation/TestAggregate.cs
- src/ReactiveDomain.Testing/Foundation/TestAggregateMessages.cs
- src/ReactiveDomain.Testing/Specifications/MockRepositorySpecification.cs
- src/ReactiveDomain.UI.Debug.nuspec
- src/ReactiveDomain.UI.Testing.Debug.nuspec
- tools/CheckAssemblyVersion.ps1
- tools/CreateNuget.ps1
fixes #42 
Fixes to Mock store
- Add explict All Stream
- Ensure all events are posted to AllStream first
- Post all Projection eventst to AllStream
- Add new AllStreamProjection that correctly handles From and CatchUp scenarios
Fixes to MockSpecification
- Exclude Projection Events inTestQueue to match current behavior
> Fix $All stream implementation in MockStreamStoreConnection

- src/ReactiveDomain.Testing/Specifications/MockRepositorySpecification.cs
Simple convenience method for getting a listener using the default stream store connection, stream name builder, and event serializer from the `MockRepositorySpecification`.
> Add convenience method for getting a listener on the mock repo

- src/ReactiveDomain.Core/IEventSource.cs
- src/ReactiveDomain.Foundation/Domain/EventDrivenStateMachine.cs
- src/ReactiveDomain.Foundation/IRepository.cs
- src/ReactiveDomain.Foundation/StreamStore/CachingRepository.cs
- src/ReactiveDomain.Foundation/StreamStore/CorrelatedStreamStoreRepository.cs
- src/ReactiveDomain.Foundation/StreamStore/IAggregateCache.cs
- src/ReactiveDomain.Foundation/StreamStore/ReadThroughAggregateCache.cs
- src/ReactiveDomain.Foundation/StreamStore/StreamStoreRepository.cs
- src/ReactiveDomain.Testing/EventStore/MockStreamStoreConnectionTests.cs
- Add Update methods to IRepository
- Update Repository and Aggregate caches classes to use Update when possible
- Add a ctor overload to CorrelatedStreamStoreRepository allowing injecting both an IRepository and an optional cache factory. This will make the class easier to use in scenarios where the CorrelatedStreamStoreRepository is being defined in a place where an IRepository has already been created or injected.
- Fix a bug in the Dispose(bool) method that would cause an exception to be thrown if no cache has been defined.
> Add support for Updating aggregates in addition to GetById in repositories

- src/ReactiveDomain.Foundation.Tests/when_serializing_with_json_message_serializer.cs
- src/ReactiveDomain.Foundation/StreamStore/JsonMessageSerializer.cs
- src/ReactiveDomain.Foundation/StreamStore/JsonMessageSerializerSettings.cs
Default to not including the Assembly Version and PublicKeyToken when serializing to allow seamless assembly versioning.
Question: Should we also all the Deserializer to relax its search and fallback to FullName?
> Add assembly version tolerance in serialization

- src/ReactiveDomain.Testing/Specifications/TestQueue.cs
In `TestQueue.WaitFor()`, the use of the `HandledTypes` property was causing problems. That property converts from `HashSet<Type>` to `Array<Type>` using `ToArray()`. The conversion occasionally throws an ArgumentException, saying "Destination array is not long enough to copy all the items in the collection. Check array index and length." This error in turn causes unit tests that use `WaitFor` to occasionally fail. Because the exception is thrown from a core .NET library, we need to work around it, which we do by using the `_handledTypes` `HashSet` directly in `WaitFor()`.
Attempts to fix #101
> Work around issue with ToArray during SpinUntil

- src/ReactiveDomain.UI.Testing/Asserts.cs
- src/ReactiveDomain.UI/Bus/ReactiveTransientSubscriber.cs
- src/ReactiveDomain.UI/ReadModel/ReadModelProperty.cs
- src/ReactiveDomain.UI/ViewObjects/CommandBuilder.cs
- src/ReactiveDomain.UI/ViewObjects/Interactions.cs
- src/ReactiveDomain.UI/ViewObjects/Threading.cs
- src/ReactiveDomain.UI/ViewObjects/UserError.cs
All `public` methods, properties, fields, enums, etc. in the ReactiveDomain.UI and ReactiveDomain.UI.Testing projects now have complete and up-to-date XML comments for Intellisense.
Also implemented a minor performance improvement in ReactiveDomain.UI.Testing.Asserts. The new code uses an expression lambda instead of a method group since the latter creates an anonymous delegate at runtime, which is slower.
> Add and update Intellisense comments in ReactiveDomain.UI and ReactiveDomain.UI.Testing classes

- src/ReactiveDomain.Foundation.Tests/when_using_caching_repository.cs
- src/ReactiveDomain.Foundation.Tests/when_using_correlated_repository.cs
- src/ReactiveDomain.Foundation/ICorrelatedRepository.cs
- src/ReactiveDomain.Foundation/IRepository.cs
- src/ReactiveDomain.Foundation/StreamStore/CachingRepository.cs
- src/ReactiveDomain.Foundation/StreamStore/CorrelatedStreamStoreRepository.cs
- src/ReactiveDomain.Foundation/StreamStore/ReadThroughAggregateCache.cs
- src/ReactiveDomain.Foundation/StreamStore/StreamStoreRepository.cs
- src/ReactiveDomain.Persistence/EventStore/EventStoreConnectionWrapper.cs
- src/ReactiveDomain.Persistence/IStreamStoreConnection.cs
- src/ReactiveDomain.Testing/EventStore/MockStreamStoreConnection.cs
Add `Delete` and `HardDelete` methods to the different repository and cache implementations to allow for simple deletion of a stream using the aggregate that's associated with that stream.
> Expose delete functionality from ES connection to aggregates

- src/ReactiveDomain.Foundation.Tests/when_using_read_model_base_with_reader.cs
- src/ReactiveDomain.Foundation/IListener.cs
- src/ReactiveDomain.Foundation/StreamStore/ReadModelBase.cs
- src/ReactiveDomain.Foundation/StreamStore/StreamListener.cs
- src/ReactiveDomain.Foundation/StreamStore/StreamReader.cs
- src/ReactiveDomain.Testing/EventStore/StreamReaderTests.cs
- Keeps existing ctor of `ReadModelBase` but tags it for future removal.
- New ctor takes an `IConfiguredConnection` instead of a `Func<IListener>`. After playing back historical events with a `StreamReader`, `ReadModelBase.Start()` switches to a `StreamListener`.
- Resolves #112.
- When starting a `StreamListener` from a checkpoint, sets the `StreamPosition` to the checkpoint before reading any events so that immediate queries will return the checkpoint as the current stream position.
- Cleans up some XML comments
> `ReadModelBase` can use a `StreamReader` for performance

- src/ReactiveDomain.Transport.Tests/ReactiveDomain.Transport.Tests.csproj
- src/ReactiveDomain.Transport.Tests/TcpBusClientSideTests.cs
- src/ReactiveDomain.Transport.Tests/TcpBusServerSideTests.cs
- src/ReactiveDomain.Transport/TcpBusClientSide.cs
Adds an `IsConnected` property to the `TcpBusClientSide` so we don't need to put in a delay or otherwise guess when a connection has been established.
> Add IsConnected to TcpBusClientSide

- src/ReactiveDomain.UI.Debug.nuspec
- src/ReactiveDomain.UI.Testing.Debug.nuspec
- src/ReactiveDomain.UI.Testing.nuspec
- src/ReactiveDomain.UI.Testing/ReactiveDomain.UI.Testing.csproj
- src/ReactiveDomain.UI.nuspec
- src/ReactiveDomain.UI/ReactiveDomain.UI.csproj
- src/ReactiveDomain.UI/ViewObjects/Threading.cs
The `Threading` class in `ReactiveDomain.UI` is only supported with .NET Framework 4.8 since it has dependencies that are unsupported in .NET Standard 2.0.
> Add netstandard2.0 support to `ReactiveDomain.UI` and `ReactiveDomain.UI.Testing` projects

- src/ReactiveDomain.Policy/Policy.cs
- src/ReactiveDomain.Policy/Role.cs
- src/ReactiveDomain.Policy/UserPolicy.cs
- src/ReactiveDomain.PolicyStorage.Tests/with_policy_user.cs
- src/ReactiveDomain.PolicyStorage/Domain/PolicyUser.cs
- src/ReactiveDomain.PolicyStorage/Domain/SecurityPolicy.cs
- src/ReactiveDomain.PolicyStorage/ReadModels/PolicyUserRm.cs
- src/ReactiveDomain.PolicyStorage/ReadModels/RoleDTO.cs
Resolves #120 
- Trim role names before persisting.
- Role name comparisons are always case-insensitive.
> Roles are case-insensitive

- src/ReactiveDomain.Debug.nuspec
- src/ReactiveDomain.IdentityStorage/Domain/Client.cs
- src/ReactiveDomain.IdentityStorage/Messages/ClientMsgs.cs
- src/ReactiveDomain.IdentityStorage/Services/ClientSvc.cs
- src/ReactiveDomain.IdentityStorage/UserExceptions.cs
- src/ReactiveDomain.Policy.Debug.nuspec
- src/ReactiveDomain.Policy.nuspec
- src/ReactiveDomain.Policy/Permissions.cs
- src/ReactiveDomain.PolicyTool/Program.cs
- src/ReactiveDomain.Testing.Debug.nuspec
- src/ReactiveDomain.Testing.nuspec
- src/ReactiveDomain.UI.Debug.nuspec
- src/ReactiveDomain.UI.Testing.Debug.nuspec
- src/ReactiveDomain.UI.Testing.nuspec
- src/ReactiveDomain.UI.nuspec
- src/ReactiveDomain.nuspec
- src/build.props
This enables us to resolve a couple of TODOs in PolicyTool.
Other changes:
- Bump version to 0.9.2.
- Add static `Permissions` class to simplify getting commands and permissions from a Msgs class.
> Add a `ClientSvc` to front the `Client` aggregate

- src/ReactiveDomain.Foundation.Tests/when_using_caching_repository.cs
- src/ReactiveDomain.Foundation/StreamStore/CachingRepository.cs
- src/ReactiveDomain.Foundation/StreamStore/IAggregateCache.cs
- src/ReactiveDomain.Foundation/StreamStore/ReadThroughAggregateCache.cs
This changes the `ReadThroughAggregateCache` so that its `Dictionary` of known aggregates indexes by a tuple of type and ID rather than just by ID. This resolves #125.
> `ReadThroughAggregateCache` indexes by both type and ID

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- SUPPORT.md
Add a number of docs that are supported automatically by GitHub to make it easier for visitors to use the repo.
- Enhanced README
- Code of conduct
- Templates for bug and feature request Issues
- Template for pull requests
- Guidelines for contributing to the project
- Brief support doc to be shown, e.g., on the New Issue page
This is a draft for now. The code of conduct needs to be updated with better contact info before this will be ready to pull.
> Add supporting docs for the repo

- src/ReactiveDomain.Foundation/Domain/AggregateRoot.cs
Uses the `Source` property to set the correlation source in the ctor of `AggregateRoot` so that the `correlationId` gets set correctly when the injected correlation source is a root message.
Uses the existing logic in the `Source` setter to ensure consistency.
When using a root message as the correlation source in the ctor of AggregateRoot, the correlation ID would not be set correctly.
**Checklist**
> Fixes setting of correlation ID in AggregateRoot ctor

- .gitignore
- build/ReactiveDomain.Policy.props
- build/ReactiveDomain.Testing.props
- build/ReactiveDomain.UI.Testing.props
- build/ReactiveDomain.UI.props
- build/ReactiveDomain.props
- src/ReactiveDomain.Debug.nuspec
- src/ReactiveDomain.Policy.Debug.nuspec
- src/ReactiveDomain.Policy.nuspec
- src/ReactiveDomain.Policy.targets
- src/ReactiveDomain.Testing.Debug.nuspec
- src/ReactiveDomain.Testing.nuspec
- src/ReactiveDomain.UI.Debug.nuspec
- src/ReactiveDomain.UI.Testing.Debug.nuspec
- src/ReactiveDomain.UI.Testing.nuspec
- src/ReactiveDomain.UI.nuspec
- src/ReactiveDomain.nuspec
- src/build.props
- tools/CreateDebugNuget.ps1
When referencing ReactiveDomain from projects using modern SDK-style csproj files, this prevents the included files from showing up in Visual Studio's solution explorer as links, which can make it difficult for developers to find their own files. This is standard practice in modern nuget packages.
Updates the nuspec files, adds .props files for each nuget package that set all `contentFiles` to be invisible, and sets items in explicit .targets files to `Visible=false`.
Polluting the solution explorer with lots of files from included nuget packages can make it difficult for developers to find their own files.
This does not …
> Add props files and set Visible to false in targets file

- src/ReactiveDomain.Foundation.Tests/when_using_read_model_base.cs
- src/ReactiveDomain.Foundation.Tests/when_using_snapshot_read_model.cs
- src/ReactiveDomain.Foundation/StreamStore/ReadModelBase.cs
- src/ReactiveDomain.Foundation/StreamStore/SnapshotReadModel.cs
- src/ReactiveDomain.IdentityStorage/ReadModels/SubjectsRm.cs
- src/ReactiveDomain.IdentityStorage/ReadModels/UsersRm.cs
- src/ReactiveDomain.IdentityStorage/Services/ClientStore.cs
- src/ReactiveDomain.PolicyStorage/ReadModels/ApplicationRm.cs
- src/ReactiveDomain.PolicyStorage/ReadModels/FilteredPoliciesRM.cs
- src/ReactiveDomain.PolicyStorage/ReadModels/PolicyUserRm.cs
Fixes a threading issue where a read model that is queried for its state could simultaneously handle an event, potentially causing an error if the query and the handler access the same aspect of the read model's state.
- Adds a `ReaderLock` property to `ReadModelBase` that can be used when reading the state of the read model.
- Adds a `Version` property to `ReadModelBase` that increments with the total number of messages passed to the read model. This can be used in tests to ensure the read model state.
- Fixes an issue in `ReadModelBase` that could cause events to be read twice if `Start` is called with a checkpoint that is already at the end of the stream. …
> Fixes threading issues with `ReadModelBase`

- src/ReactiveDomain.Persistence/EventStore/EventStoreConnectionManager.cs
- src/ReactiveDomain.Persistence/EventStore/EventStoreConnectionWrapper.cs
- src/ReactiveDomain.Persistence/IStreamStoreConnection.cs
- src/ReactiveDomain.Testing/EventStore/MockStreamStoreConnection.cs
Enables authenticated connections to ESDB instances using the standard wrapper classes in ReactiveDomain. This allows a workaround for a recent TPC connection string processing change from EventStore.
Callers to `EventStoreConnectionManager` and `EventStoreConnectionWrapper` can provide credentials for the ESDB connection.
Enables connecting to an ESDB instance that requires authentication.
"This does not address any open issues."
> Allows for providing credentials to ESDB

- src/ReactiveDomain.Foundation.Tests/when_using_read_model_base.cs
- src/ReactiveDomain.Foundation/StreamStore/ReadModelBase.cs
- src/ReactiveDomain.Testing/AssertEx.cs
Makes it easier to wait for a read model to reach a particular `Version` in unit tests. This makes for more readable and more easily reviewable code.
Adds a method to `AssertEx` to verify an RM's `Version` property.
Continued enhancement of `ReadModelBase` testability.
**Checklist**
> Adds a method to `AssertEx` to verify an RM's `Version`

- src/ReactiveDomain.Foundation.Tests/when_using_read_model_base.cs
- src/ReactiveDomain.Testing/AssertEx.cs
- src/ReactiveDomain.Testing/ConnectionUtil.cs
- src/ReactiveDomain.Testing/Specifications/TestQueue.cs
Fix multiplatform test issues from the use of spinwait
remove spinwait, use await
tests should run on all platforms
**Checklist**
> Remove SpinWait from IsOrBecomesTrue

- src/ReactiveDomain.Testing/ReactiveDomain.Testing.csproj.DotSettings
- src/ReactiveDomain.Testing/Specifications/DispatcherSpecification.cs
- src/ReactiveDomain.Testing/Specifications/MockRepositorySpecification.cs
- src/ReactiveDomain.Testing/Specifications/MockRepositoryTests.cs
Explicitly dispose of resources in test specifications
`DispatcherSpecification` and `MockRepositorySpecification` implement the `IDisposable` interface.
Test specifications predictably dispose of their resources.
**Potential breaking change**
Note that any test classes that inherit from these specification classes and then implement `IDisposable` will need to be updated to use `Dispose(bool)` so as not to hide the base class's `Dispose` method.
**Checklist**
> Test specifications implement IDisposable

- src/ReactiveDomain.Foundation.Tests/when_using_read_model_base.cs
- src/ReactiveDomain.Testing/AssertEx.cs
- src/ReactiveDomain.Testing/EventStore/StreamStoreSubscriptionTests.cs
A number of users have requested versions of the `IsOrBecomes` methods in `AssertEx` that have timeouts specified using `TimeSpan` instead of as an integer number of milliseconds.
Adds overloads of both methods. The timeouts are required for these overloads, and do not implement the deprecated `yieldThread` parameter.
Makes test code more readable.
**Checklist**
> Adds overloads with TimeSpan timeouts to AssertEx methods

- src/ReactiveDomain.Foundation/StreamStore/ReadModelBase.cs
- src/ReactiveDomain.Testing/AssertEx.cs
- src/ReactiveDomain.Testing/EventStore/MockStreamStoreConnection.cs
- src/ReactiveDomain.Testing/Specifications/NullComfiguredConnection.cs
- src/ReactiveDomain.Testing/Specifications/NullConnection.cs
- src/ReactiveDomain.Testing/Specifications/NullListener.cs
- src/ReactiveDomain.Testing/Specifications/NullReader.cs
- src/ReactiveDomain.Testing/Specifications/NullRepository.cs
- src/ReactiveDomain.Testing/Specifications/ReadModelTestSpecification.cs
- src/ReactiveDomain.Testing/Specifications/TestQueue.cs
- src/ReactiveDomain.Testing/Specifications/TestQueueTests.cs
- src/ReactiveDomain.Testing/TestVisibilityHelpers.cs
- src/ReactiveDomain.UI.Testing/ReactiveDomain.UI.Testing.csproj
- src/ReactiveDomain.UI.Testing/TestVisibilityHelpers.cs
Adds test specifications and support classes for ReadModel testing
> Enhance test specifications and support classes for testing read models

- .gitignore
- tools/CreateNuget.ps1
The CreateNuget script builds snupkg files along with nupkg files. When we use `nuget push`, they should get included automatically.
> Build symbols packages with nuget

- src/ReactiveDomain.Foundation/StreamStore/StreamReader.cs
Readers return false on missing streams (i.e. no events read)
> Ensure reads match listeners on missing stream handling

- .github/workflows/pr-checks.yml
- src/ReactiveDomain.Debug.nuspec
- src/ReactiveDomain.Policy.Debug.nuspec
- src/ReactiveDomain.Policy.nuspec
- src/ReactiveDomain.Testing.Debug.nuspec
- src/ReactiveDomain.Testing.nuspec
- src/ReactiveDomain.nuspec
- src/build.props
- tools/CreateDebugNuget.ps1
- tools/CreateNuget.ps1
Removes .NET 6 support. This leaves .NET 8 as the only target. The current plan is to only support LTS releases of .NET, but if there's enough of a reason to support .NET 9, that could be added later.
Removes .NET 6 from build.props, from the GitHub Actions config, and from the nuspec files and related scripts.
.NET 6 is out of support, and is not supported on updated build VMs.
"This does not address any open issues."
**Checklist**
> Removes .NET 6 support

- src/ReactiveDomain.Core/ReactiveDomain.Core.csproj
- src/ReactiveDomain.Foundation.Tests/ReactiveDomain.Foundation.Tests.csproj
- src/ReactiveDomain.IdentityStorage.Tests/ReactiveDomain.IdentityStorage.Tests.csproj
- src/ReactiveDomain.IdentityStorage/ReactiveDomain.IdentityStorage.csproj
- src/ReactiveDomain.Messaging.Tests/ReactiveDomain.Messaging.Tests.csproj
- src/ReactiveDomain.Messaging/ReactiveDomain.Messaging.csproj
- src/ReactiveDomain.Policy.Tests/ReactiveDomain.Policy.Tests.csproj
- src/ReactiveDomain.PolicyStorage.Tests/ReactiveDomain.PolicyStorage.Tests.csproj
- src/ReactiveDomain.PolicyStorage/ReactiveDomain.PolicyStorage.csproj
- src/ReactiveDomain.PolicyTool/ReactiveDomain.PolicyTool.csproj
- src/ReactiveDomain.Testing/ReactiveDomain.Testing.csproj
- src/ReactiveDomain.Transport.Tests/ReactiveDomain.Transport.Tests.csproj
Updates nuget package references.
Excludes `xunit.runner.visualstudio` from the updates, which can wait until we update to xunit 3 across the board. Updating before then would require lots of changes for compatibility anyway.
> Update nuget package references
